#include <device/DeviceFactory.hpp>
#include <geometry/ShapeFactory.hpp>
#include <core/Point.hpp>
#include <core/Vector.hpp>
#include <iostream>
#include <cmath>
#include <viewer/OpenGLViewer.hpp>
#include <viewer/AxisRenderable.hpp>
#include <viewer/DeviceRenderable.hpp>
#include <viewer/PointCloudRenderable.hpp>
#include <viewer/WireframeRenderable.hpp>
#include <simulation/SimulationScene.hpp>
#include <simulation/SignalSolver.hpp>
#include <core/Car.hpp>
#include <adapter/JsonAdapterRegistry.hpp>
#include <adapter/PointJsonAdapter.hpp>
#include <adapter/VectorJsonAdapter.hpp>
#include <adapter/CarJsonAdapter.hpp>