#include "Device/DeviceFactory.hpp"
#include "Geometry/ShapeFactory.hpp"
#include "Core/Point.hpp"
#include "Core/Vector.hpp"
#include <iostream>
#include <cmath>
#include "Viewer/OpenGLViewer.hpp"
#include "Viewer/AxisRenderable.hpp"
#include "Viewer/DeviceRenderable.hpp"
#include "Viewer/PointCloudRenderable.hpp"
#include "Viewer/WireframeRenderable.hpp"
#include "Simulation/SimulationScene.hpp"
#include "Simulation/SignalSolver.hpp"
